/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB.Inloggning;

import MIB.Inloggning.Sidor.AndraLosenord;
import MIB.MainFrame;
import oru.inf.InfDB;

/**
 *
 * @author Hampus
 */
public class MenyAgent extends javax.swing.JPanel {
    AndraLosenord andraLosen;
    private static InfDB idb;

    /**
     * Creates new form MenyAgent
     */
    public MenyAgent(InfDB databas) {
        initComponents();
        idb = databas;
        andraLosen = new AndraLosenord(idb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnAndraLosenord = new javax.swing.JButton();

        jbtnAndraLosenord.setText("Ändra Lösenord");
        jbtnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAndraLosenordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jbtnAndraLosenord)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jbtnAndraLosenord)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAndraLosenordActionPerformed

        // Ska köra metoden VisaAndraLosen() från MainFrame.
         //MainFrame.VisaAndraLosen();
         
        
    }//GEN-LAST:event_jbtnAndraLosenordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAndraLosenord;
    // End of variables declaration//GEN-END:variables
}
